Added 40MB check

diff --git a/.github/workflows/ubuntu-installation.yml b/.github/workflows/ubuntu-installation.yml
--- a/.github/workflows/ubuntu-installation.yml
+++ b/.github/workflows/ubuntu-installation.yml
@@ -34,7 +34,7 @@ jobs:
       - name: Verifies dotfiles (BASH)
         run: source ~/.bashrc && ./verify.zsh
 
-      - name: Calculate disk usage change
+      - name: Check disk usage
         run: |
           final_usage=$(df -h -B 1 | grep '/dev/root' | awk '{print $3}')
           echo "Final disk usage: $final_usage bytes"
@@ -42,3 +42,7 @@ jobs:
           usage_change_bytes=$((final_usage - initial_usage))
           usage_change_mb=$(echo "scale=2; $usage_change_bytes / (1024 * 1024)" | bc)
           echo "Disk usage change: $usage_change_mb MB"
+          if (( $(echo "$usage_change_mb > 40" | bc -l) )); then
+            echo "Error: Disk usage change exceeds 40MB. It is $usage_change_mb MB."
+            exit 1
+          fi
